services:
    discount-finder:
        build:
            context: .
            dockerfile: Containerfile

        container_name: discount-finder

        ports:
            - "7001:5000"

        restart: unless-stopped
